engines:
  pmd:
    enabled: true
    config:
      rules:
        - "java-basic"
        - "java-design"
        - "java-empty"
        - "java-naming"
        - "java-optimization"
        - "java-unnecessary"
        - "java-unusedcode"
ratings:
  paths:
  - "**.java"
