language: java
dist: trusty
sudo: false

jdk:
  - openjdk8
  - oraclejdk8
matrix:
  fast_finish: true

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B
script: mvn test -Dsurefire.useFile=false
after_success:
  - mvn clean cobertura:cobertura coveralls:report -Dmaven.plugin.skip=true -B

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/endpoint/c6cc872b193cbad86273/529f9078ed5ab0b3bf04ef9a/
