name: Maven CI

on:
  push:
    branches:
      - *
    paths:
      - src/main/**/*
      - .github/workflows/*
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '8', '11', '17' ]
      fail-fast: false

    name: Java ${{ matrix.java }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
        name: Set up JDK ${{ matrix.java }}

      - name: Compile with Maven
        run: mvn compile

      - name: Test with Maven
        run: mvn test
